spring:
  r2dbc:
    url: r2dbc:${DB_URL:postgresql://localhost:5432/postgres}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

lark:
  appId: ${app_id:cli_a270a6db85fad00b}
  appSecret: ${app_secret:LZxrWWcHKavl6xyGLN0behga8y0neDku}